# DO NOT TOUCH
config-version: 9

# 自动保存功能自动在设定的时间间隔保存玩家数据
# （职业、等级等）和公会数据
# （公会名称、成员等）。
auto-save:
  enabled: true
  interval: 1800 # 以秒为单位（1800 = 30分钟）
  log: true

# MySQL支持
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: minecraft
  user: mmolover
  pass: ILovePhoenixDev
  properties:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048

# 所有玩家数据的默认值
# 所有新玩家将从这些值开始
default-playerdata:
  level: 1
  class-points: 0
  skill-points: 0
  skill-realloc-points: 0
  attribute-points: 0
  attribute-realloc-points: 0
  health: 20
  mana: 0
  stellium: 0
  stamina: 0

# 所有条件的列表，这些条件必须满足
# 用于应用“BLOCK REGEN”和“BLOCK RESTRICTIONS”。设置为
# 'custom-mine-conditions: []'以完全禁用自定义挖掘。
#
# custom-mine-conditions:
# - 'world{name="__global__"}'
#
# ^ 将在整个服务器上启用自定义挖掘
custom-mine-conditions:
  - 'world{name="world,world_nether,world_the_end"}'
  - 'region{name="example_region,example_region2,__global__"}'

# 设置为true时，防止在满足自定义挖掘条件时破坏原版方块
protect-custom-mine: false

# 在此处编辑处理团队插件。
# 支持的值（只需复制粘贴）：
# - mmocore
# - dungeonsxl
# - parties
# - party_and_friends（如果你正在使用Spigot的Party and Friends扩展版，请使用此选项）
# - party_and_friends_bungeecord_velocity（如果你正在使用Bungeecord的Party and Friends，Velocity的Party and Friends或Bungeecord/Velocity的Party and Friends扩展版，请使用此选项。这需要安装https://www.spigotmc.org/resources/spigot-party-api-for-party-and-friends.39751/）
# - mcmmo
# - obteam（DungeonMMO的附加组件）
# - mythicdungeons（仅在使用默认团队处理程序时）
party-plugin: mmocore

# 在此处编辑处理公会插件。
# 支持的值（只需复制粘贴）：
# - mmocore
# - guilds
# - kingdomsx
# - ultimate_clans
guild-plugin: mmocore

# MythicLib引入了一个CHANCE状态，用于在MMOCore的多个不同系统中使用。
# 通过更改这些权重，您可以定义Chance状态对MMOCore实现的不同功能的影响程度
#
# 例如，将某些权重设置为2将在一个特定系统中使Chance状态的影响加倍。默认情况下，所有权重都设置为1，此选项确实是服务器特定的。
chance-stat-weight:
  loot-chests: 1
  fishing-drops: 1
  drop-items: 1

# 在技能树界面滚动时x和y方向的步长。
skill-tree-scroll-step-x: 1
skill-tree-scroll-step-y: 1

# 是否使“cobblegenerator”生成的方块提供玩家经验值。
should-cobblestone-generators-give-exp: false

# 在这里编辑如何施放技能。这部分配置比较复杂，因此最好在编辑任何内容之前阅读wiki页面。
skill-casting:
  mode: SKILL_BAR
  open: SWAP_HANDS
  disable-sneak: false

loot-chests:

  # 从生成后经过多少秒后，战利品箱过期。600为10分钟。
  chest-expire-time: 600

  # 同一玩家在任何地区生成两个战利品箱之前的时间间隔。
  player-cooldown: 600

# 适用于每个技能的全局冷却时间（以tick为单位）
# 将其设置为0以禁用此选项。默认情况下设置为0.5秒。这不适用于被动技能
global-skill-cooldown: 10

# 默认动作栏的设置
action-bar:

  # 是否使用默认动作栏。
  # （这不会改变MMOCore提供的其他动作栏。）
  enabled: true

  # 当显示其他动作栏时，动作栏淡出的时长（以tick为单位）。
  time-out: 60

  # 更新信息之前的ticks数。
  ticks-to-update: 5

  # 数据的显示方式。
  format: "&c❤ {health}/{max_health} &f| {mana_icon} {mana}/{max_mana} &f| &7⛨ {armor}"

party:

  # 在此处编辑团队增益。您可以添加任意数量的属性。
  buff:

    # '3' -> 生命回复增加固定 +3 点/秒
    # '3%' -> 增加当前生命回复的 3%
    health-regeneration: 3%

    # '5' -> 经验增加 5%（这是“额外经验”定义的方式）
    # '5%' -> 增加当前“%额外经验”属性的 5%（注意这种行为的区别！！！）
    # !! 注意可能导致混淆 !!
    additional-experience: 5

  # 聊天中表示发言是团队聊天时需要使用的前缀。
  chat-prefix: '@'

  # 团队中的最大玩家数量
  # 必须大于2
  max-players: 8

  # 如果玩家的等级与初始团队所有者的等级之间的差异超过此值，则该玩家无法加入团队。
  #
  # 这可以防止低等级玩家加入高等级玩家的团队并获得大量经验值。
  #
  # 如果要禁用此功能，请将其设置为可能的最大等级。
  max-level-difference: 3

  # 如果玩家距离太远，则经验不会分割。
  #
  # 设置为0以禁用
  max-exp-split-range: 48

  # 当启用时，团队中的玩家将共享职业经验
  main-exp-split: true

  # 当启用时，团队中的玩家将共享专业经验
  profession-exp-split: false

# 在未使用MMOCore作为任务插件时不相关
mmocore-quests:

  # 禁用指示当前目标的BOSS栏
  disable-boss-bar: false

# 重定向获取的原版经验到MMOCore的职业经验。
# 您可以定义转移的原版经验的百分比作为MMOCore经验。
# 更改时需要服务器重新加载。
vanilla-exp-redirection:
  enabled: false
  ratio: 0.8

# 启用此选项以覆盖原版经验并在原版经验栏上显示等级进度。
# 更改时需要服务器重新加载。
override-vanilla-exp: true

# 当启用时，并且使用了配置文件插件，则MMOCore将强制用户选择一个职业。
# 在选择职业之前将不会创建配置文件。同样，玩家不能在选择其他职业之前登录具有默认职业的配置文件。
#
# 除非您已安装配置文件插件，否则此选项无效。
force-class-selection: true

# 在shift-right click时检查目标玩家的RPG配置文件。
shift-click-player-profile-check: false

# 是否显示玩家获得主职业经验时的主职业经验全息图
display-main-class-exp-holograms: true

# 这是通过/skilltrees打开的GUI。它允许在不同的技能树之间切换。
enable-global-skill-tree-gui: true

# 这是通过/skilltrees <skilltree_id>打开的GUI。它只显示特定的技能树，不允许更改。
enable-specific-skill-tree-gui: true

# 更改时需要服务器重新加载。
death-exp-loss:
  enabled: false

  # 死亡时失去的当前经验百分比。
  percent: 30

# 最大技能槽数。这意味着您不能解锁超过X技能槽。
max-skill-slots: 8

# 当设置为true时，必须绑定被动技能才能生效。
# 当设置为false时，解锁的技能将立即生效。
# 这仅是技能的默认行为，但可以通过在职业技能部分中指定true/false来覆盖。
passive-skill-need-bound: true

# 将此选项设置为true，允许创造模式下的玩家进入施放模式
can-creative-cast: false

# 阻止从刷怪笼生成的生物提供MMO XP点。
prevent-spawner-xp: true

combat-log:

  # 战斗记录过期的计时器（以秒为单位）
  timer: 10

  # 触发战斗记录的伤害原因列表（List: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html）
  causes:
    - CRAMMING
    - DRAGON_BREATH
    - ENTITY_ATTACK
    - ENTITY_EXPLOSION
    - ENTITY_SWEEP_ATTACK
    - MAGIC
    - POISON
    - PROJECTILE
    - SONIC_BOOM
    - THORNS
    - WITHER

# 是否应该在选择新职业时保存默认职业的信息（等级、技能等）
save-default-class-info: false

# 使用路径点传送所需的时间（以tick为单位）。
waypoint-warp-time: 100

# 将此更改为您希望为不同资源栏占位符使用的颜色名称
resource-bar-colors:
  stamina-whole: 'GREEN'
  stamina-half: 'DARK_GREEN'
  stamina-empty: 'WHITE'

# 是否在运行管理员命令时显示命令的结果。
# 例如：“Players Level is now 10.”
# 接受的值：
# true - 始终显示详细信息
# player - 仅当玩家运行时显示详细信息
# console - 仅当从控制台运行时显示详细信息
# false - 从不显示详细信息
command-verbose:
  attribute: true
  skill: true
  class: true
  experience: true
  level: true
  nocd: true
  skill-tree-points: true
  points: true
  reset: true
  resource: true
  waypoint: true

# 需要WorldGuard才能工作。除非您有WG，否则请勿启用，以避免奇怪的交互规则问题！
#
# 更多信息，请参阅wiki
# https://gitlab.com/phoenix-dvpmt/mmocore/-/wikis/Combat#pvp-mode
pvp_mode:

  # 更改时需要/reload
  enabled: false

  # 最低等级以与其他玩家战斗。
  # 设置为0以完全禁用
  min_level: 0

  # 最大等级差异以与其他玩家战斗。
  # 设置为0以完全禁用
  max_level_difference: 10

  # 攻击后在该时间内玩家将保持在PvP模式中（以秒为单位）
  # 必须低于'cooldown.combat'
  combat_timeout: 30

  # 当：
  # - 进入开启PvP模式的PvP区域。
  # - 在PvP区域内使用/pvpmode命令。
  # 触发无敌状态
  invulnerability:
    time:
      region_change: 60
      command: 30

# 当启用时，玩家可以对其他玩家造成伤害
# 以结束无敌时间段。
can_damage: false

# 当启用时，离开无PVP区域并进入PVP区域
# 将应用相同的无敌时间。
# 更改时需要/reload
apply_to_pvp_flag: true

cooldown:

  # 进入PvP模式区域时在能够使用/pvpmode命令之前的冷却时间。
  region_enter: 20

  # 离开PvP模式区域时在能够使用/pvpmode命令之前的冷却时间。
  region_leave: 20

  # 在进入战斗后能够使用/pvpmode的延迟时间（以秒为单位）。
  # 必须大于'combat_timeout'
  combat: 45

  # 在切换开启PvP模式时，在能够切换关闭PvP模式之前的冷却时间（以秒为单位）
  toggle_on: 5

  # 在切换关闭PvP模式时的冷却时间（以秒为单位）
  toggle_off: 3