# 中文重制版 By Happy Github: https://github.com/Happy-clo/
name: MMOCore
version: ${project.version}
main: net.Indyuce.mmocore.MMOCore
author: Indyuce
description: ${project.description}
loadbefore: [ MMOItems,MythicDungeons ]
depend: [ MythicLib ]
softdepend: [ Vault,MythicMobs,MMOProfiles,PlaceholderAPI,Residence,Citizens,ProtocolLib,OBTeam ]
api-version: 1.13
commands:
  mmocore:
    description: 主命令。
    aliases: [rpg]
permissions:
  mmocore.admin:
    description: 允许使用 /mmocore 命令
    default: op
  mmocore.waypoints:
    description: 允许使用 /waypoints 命令
    default: op
  mmocore.pvpmode:
    description: 允许使用 /pvpmode 命令
    default: op
  mmocore.currency:
    description: 允许使用 /deposit 和 /withdraw 命令
    default: op
  mmocore.bypass-waypoint-wait:
    description: 绕过路径点等待时间
    default: op
  mmocore.class-select:
    description: 允许使用 /class 命令
    default: op
  mmocore.attributes:
    description: 允许使用 /attributes 命令
    default: true
  mmocore.skills:
    description: 允许使用 /skills 命令
    default: true
  mmocore.profile:
    description: 允许使用 /profile 命令
    default: true
  mmocore.friends:
    description: 允许使用 /friends 命令
    default: true
  mmocore.guild:
    description: 允许使用 /guild 命令
    default: true
  mmocore.party:
    description: 允许使用 /party 命令
    default: true
  mmocore.skilltrees:
    description: 允许使用 /skilltrees 命令
    default: true
  mmocore.quests:
    description: 允许使用 /quests 命令
    default: true
