name: Build Origin Version

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        jdkversion: [17]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdkversion }}
        cache: 'maven'
        
    - name: Configure Git User Details
      run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
    - name: Remove
      run: rm target/* -f
    - name: Build with Maven
      run: |
          git clone https://gitlab.com/phoenix-dvpmt/mmocore.git core
          cd core
          mvn -V -B clean package --file pom.xml
    - name: upload
      uses: actions/upload-artifact@v3
      with:
       name: MMOCore
       path: core/target
